home:
  href: home
  title: Welcome to ExpensifyHelp!
  description: Find answers using the search bar or click on the version of Expensify you're using to access the relevant resources.

# "Getting Started" and "Topics" cards shown on the homepage
getting-started:
  - title: For employees
    icon: /assets/images/simple-illustration__approval-members.svg
    description: Join a workspace, submit expenses and enable 2FA.
    href: /articles/new-expensify/getting-started/Join-your-company's-workspace

  - title: For admins
    icon: /assets/images/simple-illustration__company-share-alt.svg
    description: Create a workspace, connect accounting and configure approvals.
    href: /articles/new-expensify/getting-started/Create-a-company-workspace

  - title: With payments
    icon: /assets/images/simple-illustration__cardreader-alt2-alt.svg
    description: Link a business bank account to enable reimbursements and the Expensify Card.
    href: /articles/new-expensify/wallet-and-payments/Connect-a-Business-Bank-Account

topics:
  - title: Expense management
    icon: /assets/images/simple-illustration__money-receipt.svg
    hub: /new-expensify/hubs/reports-and-expenses/
    links:
      - label: Create expenses
        href: /articles/new-expensify/reports-and-expenses/Create-an-Expense
      - label: Submit expense reports
        href: /articles/new-expensify/reports-and-expenses/Create-and-Submit-Reports
      - label: Pay expenses
        href: /articles/new-expensify/wallet-and-payments/Pay-Expenses

  - title: Expensify Card
    icon: /assets/images/simple-illustration__creditcards--green.svg
    hub: /new-expensify/hubs/expensify-card/
    links:
      - label: Enable Expensify Cards
        href: /articles/new-expensify/expensify-card/Set-Up-and-Manage-the-Expensify-Card
      - label: Activate and use cards
        href: /articles/new-expensify/expensify-card/Cardholder-Settings-and-Features
      - label: Reconcile transactions
        href: /articles/new-expensify/expensify-card/View-and-Reconcile-Expensify-Card-Expenses

  - title: Company cards
    icon: /assets/images/simple-illustration__twocards-horizontal.svg
    hub: /new-expensify/hubs/connect-credit-cards/
    links:
      - label: Connect commercial feed
        href: /articles/new-expensify/connect-credit-cards/Commercial-feeds
      - label: Connect directly
        href: /articles/new-expensify/connect-credit-cards/Direct-feeds
      - label: Map cards to GL
        href: /articles/new-expensify/connect-credit-cards/Company-Card-Settings

  - title: Accounting
    icon: /assets/images/simple-illustration__monitor-remotesync.svg
    hub: /new-expensify/hubs/connections/
    links:
      - label: Connect to NetSuite
        href: /articles/new-expensify/connections/netsuite/Connect-To-NetSuite
      - label: Connect to QuickBooks Online
        href: /articles/new-expensify/connections/quickbooks-online/Connect-to-QuickBooks-Online
      - label: Connect to Xero
        href: /articles/new-expensify/connections/xero/Connect-to-Xero

  - title: Workflows
    icon: /assets/images/workflow.svg
    hub: /new-expensify/hubs/workspaces/
    links:
      - label: Configure rules
        href: /articles/new-expensify/workspaces/Workspace-Rules
      - label: Automation and approvals
        href: /articles/new-expensify/workspaces/Workspace-Workflows
      - label: Prohibited expense detection
        href: /articles/new-expensify/workspaces/Prohibited-Expense-Rule

  - title: Back-office
    icon: /assets/images/simple-illustration__buildings.svg
    hub: /new-expensify/hubs/settings/
    links:
      - label: Reporting
        href: /articles/new-expensify/reports-and-expenses/Getting-Started-with-the-Reports-Page
      - label: Configure taxes
        href: /articles/new-expensify/workspaces/Track-Taxes
      - label: Nominate vacation delegate
        href: /articles/new-expensify/settings/Delegate-when-out-of-office

  - title: Travel
    icon: /assets/images/simple-illustration__luggage.svg
    hub: /travel/hubs/
    links:
      - label: Use Expensify Travel
        href: /travel/hubs/getting-started/
      - label: Set up Per Diems
        href: /articles/new-expensify/workspaces/Configure-Per-Diem-in-a-workspace
      - label: Configure mileage
        href: /articles/new-expensify/workspaces/Set-distance-rates

  - title: Chat
    icon: /assets/images/simple-illustration__commentbubbles-alt.svg
    hub: /new-expensify/hubs/chat/
    links:
      - label: Chat with people
        href: /articles/new-expensify/chat/Create-a-New-Chat
      - label: Chat basics
        href: /articles/new-expensify/chat/Chat-Features-and-Moderation-Tools
      - label: Organize your Inbox
        href: /articles/new-expensify/chat/Prioritize-and-Pin-Chats

  - title: Reporting
    icon: /assets/images/envelope-receipt.svg
    hub: /new-expensify/hubs/reports-and-expenses/
    links:
      - label: Search and filter
        href: /articles/new-expensify/reports-and-expenses/Using-Reports-in-New-Expensify
      - label: Export data
        href: /articles/new-expensify/reports-and-expenses/Search-and-Download-Expenses
      - label: Reconciliation
        href: /articles/new-expensify/reports-and-expenses/Statement-Matching-and-Reconciliation

platforms:
  - href: expensify-classic
    title: Expensify Classic
    hub-title: Expensify Classic - Help & Resources
    hub-description: Questions? Find the answers by clicking a Category or using the search bar located in the left-hand menu.
    url: www.expensify.com
    description: "Your account settings look like this:"
    image: /assets/images/settings-old-dot.svg
  
    # Hubs are comprised of subcategories and articles. Subcategories contain multiple related articles, but there can be standalone articles as well
    hubs:
      - href: getting-started
        title: Getting Started
        icon: /assets/images/accounting.svg
        description: Set up your account to optimize Expensify's features.

      - href: workspaces
        title: Workspaces
        icon: /assets/images/shield.svg
        description: Configure rules, settings, and limits for your company’s spending.

      - href: expenses
        title: Expenses
        icon: /assets/images/money-into-wallet.svg
        description: Learn more about expense tracking and submission.

      - href: reports
        title: Reports
        icon: /assets/images/money-receipt.svg
        description: Set approval workflows and use Expensify’s automated report features.

      - href: domains
        title: Domains
        icon: /assets/images/domains.svg
        description: Claim and verify your company’s domain to access additional management and security features.
      
      - href: bank-accounts-and-payments
        title: Bank Accounts & Payments
        icon: /assets/images/send-money.svg
        description: Send direct reimbursements, pay invoices, and receive payment.

      - href: connect-credit-cards
        title: Connect Credit Cards
        icon: /assets/images/bank-card.svg
        description: Track credit card transactions and reconcile company cards.

      - href: expensify-card
        title: Expensify Card
        icon: /assets/images/hand-card.svg
        description: Explore the perks and benefits of the Expensify Card.

      - href: copilots-and-delegates
        title: Copilots & Delegates
        icon: /assets/images/envelope-receipt.svg
        description: Assign Copilots and delegate report approvals.

      - href: expensify-partner-program
        title: Expensify Partner Program
        icon: /assets/images/handshake.svg
        description: Discover the benefits of becoming an Expensify Partner.

      - href: connections
        title: Connections
        icon: /assets/images/simple-illustration__monitor-remotesync.svg
        description: Integrate with accounting or HR software to streamline expense approvals.

      - href: spending-insights
        title: Spending Insights
        icon: /assets/images/monitor.svg
        description: Create custom export templates to understand spending insights.

      - href: settings
        title: Settings
        icon: /assets/images/gears.svg
        description: Manage profile settings and notifications.

      - href: expensify-billing
        title: Expensify Billing
        icon: /assets/images/subscription-annual.svg
        description: Review Expensify's subscription options, plan types, and payment methods.

        
  - href: new-expensify
    title: New Expensify
    hub-title: New Expensify - Help & Resources
    hub-description: Questions? Find the answers by clicking a Category or using the search bar.
    url: new.expensify.com
    description: "Your account settings look like this:"
    image: /assets/images/help-new.png
  
    hubs:
      - href: getting-started
        title: Getting Started
        icon: /assets/images/accounting.svg
        description: Set up your account to optimize Expensify's features.

      - href: chat
        title: Chat
        icon: /assets/images/chat-bubble.svg
        description: Use Expensify's chat feature to split bills, chat with employees, and manage payments.

      - href: concierge-ai
        title: Concierge AI
        icon: /assets/images/simple-illustration__concierge-bot.svg
        description: Learn about Concierge AI and what it can do.

      - href: workspaces
        title: Workspaces
        icon: /assets/images/shield.svg
        description: Configure rules, settings, and limits for your company’s spending.

      - href: insights
        title: Insights
        icon: /assets/images/monitor.svg
        description: Get insight into company expenses to track spend patterns and stay informed. 
      
      - href: reports-and-expenses
        title: Reports & Expenses
        icon: /assets/images/envelope-receipt.svg
        description: Learn more about expense tracking and submission.
      
      - href: domains
        title: Domains
        icon: /assets/images/domains.svg
        description: Claim and verify your company’s domain to access additional management and security features.

      - href: wallet-and-payments
        title: Wallet & Payments
        icon: /assets/images/money-into-wallet.svg
        description: Send and receive payments.

      - href: connect-credit-cards
        title: Connect Credit Cards
        icon: /assets/images/bank-card.svg
        description: Track credit card transactions and reconcile company cards.
        
      - href: expensify-card
        title: Expensify Card
        icon: /assets/images/hand-card.svg
        description: Explore the perks and benefits of the Expensify Card.

      - href: connections
        title: Connections
        icon: /assets/images/simple-illustration__monitor-remotesync.svg
        description: Connect to accounting software to streamline expense approvals.

      - href: settings
        title: Settings
        icon: /assets/images/gears.svg
        description: Manage profile settings and notifications.
        
      - href: billing-and-subscriptions
        title: Expensify Billing & Subscriptions
        icon: /assets/images/subscription-annual.svg
        description: Review Expensify's subscription options, plan types, and payment methods.
        
  - href: travel
    title: Expensify Travel
    hub-title: Expensify Travel
    hub-description: Questions? Find the answers by clicking a Category or using the search bar.
    url: travel.expensify.com
    description: "Get the help you need to book and manage travel."
    image: /assets/images/help-travel.png
  
    hubs:
      - href: getting-started
        title: Getting Started
        icon: /assets/images/accounting.svg
        description: "Learn how to get started with Expensify Travel."

      - href: booking-travel
        title: Booking with Expensify Travel
        icon: /assets/images/simple-illustration__luggage.svg
        description: "Everything you need to know about booking flights, hotels, and more with Expensify Travel."

      - href: managing-trips
        title: Managing trips
        icon: /assets/images/plane.svg
        description: "Learn how to easily manage, modify, or cancel your trips."

      - href: company-setup
        title: Setting up your company in Expensify Travel
        icon: /assets/images/gears.svg
        description: "Set up your company to manage departments, users, booking restrictions, and more."

      - href: travel-policy
        title: Creating a travel policy
        icon: /assets/images/simple-illustration__rules.svg
        description: "Create a clear, effective travel policy for employee bookings."

      - href: travel-analytics
        title: Travel Analytics
        icon: /assets/images/simple-illustration__chart.svg
        description: "Track spend, spot savings, and drive smarter bookings with travel analytics."

      - href: event-management
        title: Event Management
        icon: /assets/images/envelope-receipt.svg
        description: "Learn how to create and manage Travel Events for group bookings."
