home:
  href: home
  title: Need some help?
  description: Explore the menu or search for a specific topic. 

platforms:
  - href: expensify-classic
    title: Expensify Classic
    hub-title: Expensify Classic - Help & Resources
    hub-description: Need some help? Explore the menu or search for a specific topic.
    url: www.expensify.com
    image: /assets/images/settings-old-dot.svg
  
    # Hubs are comprised of subcategories and articles. Subcategories contain multiple related articles, but there can be standalone articles as well
    hubs:
      - href: getting-started
        title: Getting Started
        icon: /assets/images/accounting.svg

      - href: account-settings
        title: Account Settings
        icon: /assets/images/gears.svg

      - href: bank-accounts-and-credit-cards
        title: Bank Accounts & Credit Cards
        icon: /assets/images/bank-card.svg

      - href: billing-and-subscriptions
        title: Billing & Subscriptions
        icon: /assets/images/subscription-annual.svg

      - href: expense-and-report-features
        title: Expense & Report Features
        icon: /assets/images/money-receipt.svg

      - href: expensify-card
        title: Expensify Card
        icon: /assets/images/hand-card.svg

      - href: expensify-partner-program
        title: Expensify Partner Program
        icon: /assets/images/handshake.svg

      - href: get-paid-back
        title: Get Paid Back
        icon: /assets/images/money-into-wallet.svg

      - href: insights-and-custom-reporting
        title: Insights & Custom Reporting
        icon: /assets/images/monitor.svg

      - href: integrations
        title: Integrations
        icon: /assets/images/workflow.svg

      - href: manage-employees-and-report-approvals
        title: Manage Employees & Report Approvals
        icon: /assets/images/envelope-receipt.svg
      
      - href: send-payments
        title: Send Payments
        icon: /assets/images/send-money.svg
      
      - href: workspace-and-domain-settings
        title: Workspace & Domain Settings
        icon: /assets/images/shield.svg
  
  - href: new-expensify
    title: New Expensify
    hub-title: New Expensify - Help & Resources
    hub-description: Need some help? Explore the menu or search for a specific topic.
    url: new.expensify.com
    image: /assets/images/settings-new-dot.svg
  
    hubs:
      - href: chat
        title: Chat
        icon: /assets/images/chat-bubble.svg

      - href: account-settings
        title: Account Settings
        icon: /assets/images/gears.svg

      - href: bank-accounts
        title: Bank Accounts
        icon: /assets/images/bank-card.svg
      
      - href: billing-and-plan-types
        title: Billing & Plan Types
        icon: /assets/images/subscription-annual.svg
      
      - href: expensify-card
        title: Expensify Card
        icon: /assets/images/hand-card.svg

      - href: payments
        title: Payments
        icon: /assets/images/money-into-wallet.svg
