home:
  href: home
  title: Welcome to the New Expensify!
  description: Find the answers to all of your questions about receipts, expenses, corporate cards, or anything else in the spend management universe.

# Hubs are comprised of sections and articles. Sections contain multiple related articles, but there can be standalone articles as well
hubs:
  - href: send-money
    title: Send money
    description: With only a couple of clicks, send money to your friends or coworkers using NewExpensify.
    icon: /assets/images/paper-airplane.svg
    sections:
      - href: workspaces
        title: Workspaces
        articles:
          - href: The-Free-Plan
            title: The Free Plan

  - href: request-money
    title: Request money
    icon: /assets/images/money-case.svg
    description: Request money for work expenses, bills, or a night out with friends using NewExpensify.

  - href: other
    title: Other
    description: Everything else you're looking for is right here.
    icon: /assets/images/lightbulb.svg
    articles:
      - href: Account-Management
        title: Account Management
