title: Expensify Help
tagline: Expensify Help - all your Expensify questions answered in one place.
description: Got a question about receipts, expenses, corporate cards, or anything else in the spend management universe? Get answers at help.expensify.com.
url: https://help.expensify.com
author: Expensify
logo: /assets/images/expensify-help.svg
repository: Expensify/App
open_url: true
main_style: /assets/css/styles.css

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      image: /assets/images/og-preview-image.png

exclude: [README.md, TEMPLATE.md, vendor]

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
  - jekyll-seo-tag
