name: ğŸ§™ Check spell

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: ğŸ” spellcheck
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*"
          root: "."
          config: "./cspell.json"
          inline: error
          strict: true
          use_cspell_files: false
          incremental_files_only: false