name: Post build has been started comment

on:
  workflow_call:
    inputs:
      APP_PULL_REQUEST_NUMBER:
        description: Number of the Pull Request in the App repository where the comment will be posted
        type: string
        required: false
      HYBRIDAPP_PULL_REQUEST_NUMBER:
        description: Number of the Pull Request in the Mobile-Expensify repository where the comment will be posted
        type: string
        required: false

jobs:
    postGitHubCommentBuildStarted:
        runs-on: ubuntu-latest
        steps:
        - name: Add build start comment to ND PR
          if: ${{ inputs.APP_PULL_REQUEST_NUMBER != ''}}
          # v7
          uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
          with:
            github-token: ${{ github.token }}
            script: |
                const workflowURL = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
                github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ inputs.APP_PULL_REQUEST_NUMBER }},
                body: `ðŸš§ @${{ github.actor }} has triggered a test app build. You can view the [workflow run here](${workflowURL}).`
                });

        - name: Add build start comment to OD PR
          if: ${{ inputs.HYBRIDAPP_PULL_REQUEST_NUMBER != '' }}
          # v7
          uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
          with:
            github-token: ${{ secrets.OS_BOTIFY_TOKEN }}
            script: |
                const workflowURL = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
                github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: 'Mobile-Expensify',
                issue_number: ${{ inputs.HYBRIDAPP_PULL_REQUEST_NUMBER }},
                body: `ðŸš§ @${{ github.actor }} has triggered a test hybrid app build. You can view the [workflow run here](${workflowURL}).`
                });