name: ProposalPolice™ - Issue Comment Workflow
on:
  issue_comment:
    types: [created, edited]

jobs:
  proposal-police-workflow:
    runs-on: ubuntu-latest
    if: "!contains(fromJSON('[\"OSBotify\", \"imgbot[bot]\", \"melvin-bot[bot]\", \"codecov[bot]\"]'), github.actor)"
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      # Checks if the comment is created and follows the template OR
      # if the comment is edited and if proposal template is followed.
      # Action type logic can be found in the script files.
      - name: Run ProposalPolice™ Comment Check Script
        uses: ./.github/actions/javascript/proposalPoliceComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROPOSAL_POLICE_API_KEY: ${{ secrets.PROPOSAL_POLICE_API_KEY }}
          PROPOSAL_POLICE_ASSISTANT_ID: ${{ secrets.PROPOSAL_POLICE_ASSISTANT_ID }}
