name: React Compiler Compliance Check

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths: ["**.tsx"]

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('{0}-{1}', github.ref, github.sha) || github.ref }}-react-compiler-compliance
  cancel-in-progress: true
jobs:
  react-compiler-compliance:
    name: React Compiler Compliance
    if: ${{ github.actor != 'OSBotify' }}
    runs-on: ubuntu-latest

    steps:
      # v4
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode

      - name: Run React Compiler Compliance Check
        run: npm run react-compiler-compliance-check check-changed
        env:
          CI: true
          GITHUB_TOKEN: ${{ github.token }}
