name: Reassure Performance Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths-ignore: [docs/**, .github/**, contributingGuides/**, tests/**, workflow_tests/**, '**.md', '**.sh']

jobs:
  perf-tests:
    if: ${{ github.actor != 'OSBotify' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: ./.github/actions/composite/setupNode

      - name: Set dummy git credentials
        run: |
            git config --global user.email "test@test.com"
            git config --global user.name "Test"

      - name: Run performance testing script
        shell: bash
        run: |
          set -e
          BASELINE_BRANCH=${BASELINE_BRANCH:="main"}
          git fetch origin "$BASELINE_BRANCH" --no-tags --depth=1
          git switch "$BASELINE_BRANCH"
          npm install --force
          npx reassure --baseline
          git switch --force --detach -
          git merge --no-commit --allow-unrelated-histories "$BASELINE_BRANCH" -X ours
          npm install --force
          npx reassure --branch

      - name: Read output.json
        id: reassure
        uses: juliangruber/read-file-action@v1
        with:
          path: .reassure/output.json

      - name: Validate output.json
        id: validateReassureOutput
        uses: ./.github/actions/javascript/validateReassureOutput
        with:
          DURATION_DEVIATION_PERCENTAGE: 20
          COUNT_DEVIATION: 0
          REGRESSION_OUTPUT: ${{ steps.reassure.outputs.content }}

