name: Remote Build iOS Hybrid

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-15-xlarge
    steps:
      - name: Checkout
        # v4
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.OS_BOTIFY_TOKEN }}

      - name: Setup NodeJS
        uses: ./.github/actions/composite/setupNode

      - name: RNEF Remote Build - iOS
        uses: callstackincubator/ios@v1
        env:
          PROJECT_ROOT_PATH: "Mobile-Expensify/"
        with:
          destination: simulator
          scheme: 'Expensify Dev'
          configuration: Debug
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-bot: false
