name: Send Reassure Performance Tests to Graphite

on:
  push:
    branches: [main]
    paths-ignore: [docs/**, help/**, contributingGuides/**, jest/**]

jobs:
  perf-tests:
    if: ${{ github.actor != 'OSBotify' }}
    runs-on: ubuntu-latest-reassure-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: ./.github/actions/composite/setupNode

      - name: Install dependencies
        run: npm install

      - name: Run performance testing script
        shell: bash
        run: |
          set -e
          NODE_OPTIONS=--experimental-vm-modules npx reassure --baseline

      - name: Get merged pull request
        id: getMergedPullRequest
        uses: actions-ecosystem/action-get-merged-pull-request@59afe90821bb0b555082ce8ff1e36b03f91553d9
        with:
          github_token: ${{ github.token }}

      - name: Get and save graphite string
        id: saveGraphiteString
        uses: ./.github/actions/javascript/getGraphiteString
        with:
          PR_NUMBER: ${{ steps.getMergedPullRequest.outputs.number }}

      - name: Send graphite data
        run: echo -e "${{ steps.saveGraphiteString.outputs.GRAPHITE_STRING }}" | nc -q0 stats.expensify.com 3003
