name: Temp workflow for debugging

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  jobOne:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello'

  jobTwo:
    needs: jobOne
    runs-on: ubuntu-latest
    steps:
      - run: echo ' world!'
