name: Create a new version

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-16.04

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.BOTIFY_TOKEN }}

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Install dependenices
              run: npm install

            - name: Set up git
              run: |
                git fetch
                git checkout master
                git config user.name botify

            - name: Checkout new branch
              run: git checkout -b version-bump-${{ github.sha }}

            - name: Generate version
              run: npm version prerelease -m "Update version to %s"

            - name: Save new version
              run: |
                npm run print-version --silent > web/version.txt
                git add web/version.txt
                git commit -m "Save version $(cat web/version.txt) to file"

            - name: Push new version
              run: git push --set-upstream origin version-bump-${{ github.sha }}

            - name: Push tags
              run: git push --tags

            - name: Create Pull Request
              uses: repo-sync/pull-request@v2
              with:
                    source_branch: version-bump-${{ github.sha }}
                    destination_branch: "master"
                    pr_label: "automerge"
                    github_token: ${{ secrets.BOTIFY_TOKEN }}

            # This Slack step is duplicated in all workflows, if you make a change to this step, make sure to update all
            # the other workflows with the same change
            - uses: 8398a7/action-slack@v3
              name: Job failed Slack notification
              if: ${{ failure() }}
              with:
                    status: custom
                    fields: workflow, repo
                    custom_payload: |
                        {
                          attachments: [{
                            color: "#DB4545",
                            text: `ðŸ’¥ ${process.env.AS_REPO} failed on ${process.env.AS_WORKFLOW} workflow ðŸ’¥`,
                          }]
                        }
              env:
                    GITHUB_TOKEN: ${{ github.token }}
                    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
