name: Create a new version

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-16.04

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Install dependenices
              run: npm install

            - name: Set git user
              run: git config user.name github-action

            - name: Checkout new branch
              run: git checkout -b version-${{ github.sha }}

            - name: Generate version
              run: npm --no-git-tag-version version prerelease -m "Update version to %s"

            - name: Push new version
              run: git push --set-upstream origin version-${{ github.sha }}

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                    labels: automerge
                    branch: version-${{ github.sha }}
                    base: master
