name: Create a new version

on: push

jobs:
    version:
        runs-on: ubuntu-16.04

        steps:
            # Version: 2.3.4
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
              with:
                  fetch-depth: 0
                  token: ${{ secrets.OS_BOTIFY_TOKEN }}

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Install dependenices
              run: npm ci

            - name: Set up git
              run: |
                git fetch
                git checkout master
                git config user.name botify

#            - name: Checkout new branch
#              run: git checkout -b version-bump-${{ github.sha }}

            - name: Generate version
              uses: Expensify/Expensify.cash/.github/actions/bumpVersion@0170a212f2af88ea6be12517b81525489646e6f2

#            - name: Push new version
#              run: git push --set-upstream origin version-bump-${{ github.sha }}
#
#            - name: Push tags
#              run: git push --tags
#
#            - name: Create Pull Request
#              # Version: 2.4.3
#              uses: repo-sync/pull-request@33777245b1aace1a58c87a29c90321aa7a74bd7d
#              with:
#                    source_branch: version-bump-${{ github.sha }}
#                    destination_branch: "master"
#                    pr_label: "automerge"
#                    github_token: ${{ secrets.OS_BOTIFY_TOKEN }}
#
#            # This Slack step is duplicated in all workflows, if you make a change to this step, make sure to update all
#            # the other workflows with the same change
#            - uses: 8398a7/action-slack@v3
#              name: Job failed Slack notification
#              if: ${{ failure() }}
#              with:
#                    status: custom
#                    fields: workflow, repo
#                    custom_payload: |
#                        {
#                          channel: '#announce',
#                          attachments: [{
#                            color: "#DB4545",
#                            pretext: `<!here>`,
#                            text: `ðŸ’¥ ${process.env.AS_REPO} failed on ${process.env.AS_WORKFLOW} workflow ðŸ’¥`,
#                          }]
#                        }
#              env:
#                    GITHUB_TOKEN: ${{ github.token }}
#                    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
